source 'https://rubygems.org'

gem 'celluloid-io'
gem 'dotenv', '~> 2.2', '>= 2.2.1'
gem 'http'
gem 'httparty'
gem 'json'
gem 'pry'
gem 'puma'
gem 'rspec', '~> 3.9'
gem 'rubocop', '~>0.81.0'
gem 'sinatra', '~> 2.0.2'
gem 'slack-ruby-bot'
gem 'slack-ruby-client', '~> 0.15.0'
